name: Python Pipeline

on:
  push:
    branches:
      - 'feature*'
      - 'develop'
      - 'main'
      - 'release*'
  pull_request:
    branches:
      - 'feature*'
      - 'develop'
      - 'main'
      - 'release*'
      - 'hotfix*'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python version
      uses : actions/setup-python@main
      with:
        python-version : '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pydocstyle pytest

    - name: Run Pylint
      run: |
        echo "Running Pylint..."
        pylint $(find . -type f -name "*.py")

    - name: Run pydocstyle
      run: |
        echo "Running pydocstyle..."
        pydocstyle .

    # - name: Run unit tests
    #   run: |
    #     echo "Running unit tests..."
    #     pytest --maxfail=5 --disable-warnings
